name: Build PHP

on:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/**.yml"
      - "docker/**"

jobs:
  integration:
    name: Build PHP ${{ matrix.php-versions }} for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ "8.2.8" ]
        arch: [ "x86_64" ]
    steps:
      - uses: actions/checkout@v2
      - name: Check Dockerfile to ${{ matrix.arch }}
        run: |
          cd docker/
          if [[ "${{ matrix.arch }}" != "x86_64" ]]; then
            if [[ "${{ matrix.arch }}" = "armv7l" ]]; then
              sed -ie 's/alpine:latest/multiarch\/alpine:armv7-latest-stable/g' Dockerfile
            else
              sed -ie 's/alpine:latest/multiarch\/alpine:${{ matrix.arch }}-v3.16/g' Dockerfile
            fi
            docker run --rm --privileged multiarch/qemu-user-static:register --reset
          fi
      - name: Build micro and PHP distribution ${{ matrix.php-versions }} for ${{ matrix.arch }}
        id: buildphp
        run: |
          cd docker/ && docker build . --tag static-php --build-arg USE_BACKUP_ADDRESS=yes && \
            mkdir ../dist && \
            docker run --rm -v $(pwd)/../dist:/dist/ static-php build-php original ${{ matrix.php-versions }} all /dist/
      - name: Fail if anything failed
        if: steps.buildphp == 'failure'
        run: |
          false
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: static-php-cli_${{ matrix.php-versions }}_${{ matrix.arch }}
          path: |
            dist
      - name: Pack PHP ${{ matrix.php-versions }} to archive
        run: |
          cd dist
          tar -zcvf "php-${{ matrix.php-versions }}-static-bin-${{ matrix.arch }}.tar.gz" ./php && rm ./php
          if [ -f "./micro.sfx" ]; then
            tar -zcvf "micro-${{ matrix.php-versions }}-${{ matrix.arch }}.tar.gz" ./micro.sfx && rm ./micro.sfx
          fi
      - name: Remove dist directory
        run: |
          rm -rf dist/
          docker images | grep -v REPOSITORY | awk '{print $3}' | xargs docker rmi --force
